# Generated by Django 3.2.2 on 2021-07-06 19:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='C:\\Users\\Admin\\Desktop\\Python\\HubInter\\hubinter\\media/default_pictures/default_avatar.jpg', upload_to='avatars/%Y/%m', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg', 'svg', 'gmp'])], verbose_name='Avatar'),
        ),
    ]
