# Generated by Django 3.2.2 on 2021-08-01 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0005_auto_20210730_2327'),
        ('accounts', '0003_alter_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='viewed_yt_videos',
            field=models.ManyToManyField(related_name='yt_viewed_by', to='videos.YoutubeVideo', verbose_name='Viewed YouTube videos'),
        ),
    ]
