# Generated by Django 3.2.2 on 2021-08-04 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_viewed_yt_videos'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='subscribers_amount',
            field=models.PositiveIntegerField(default=0, verbose_name='Subscribers amount'),
        ),
    ]
