# Generated by Django 3.2.2 on 2021-08-27 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_subscribers_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='subscribers_amount',
        ),
    ]
