# Generated by Django 3.2.2 on 2021-10-01 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_user_subscribers_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='social_authed',
            field=models.BooleanField(default=False, verbose_name='Logged in via social networks'),
        ),
    ]
