# Generated by Django 3.2.2 on 2021-07-13 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='YoutubeVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iframe_code', models.TextField(verbose_name="Video's HTML code")),
                ('title', models.CharField(max_length=255, verbose_name='Youtube Title')),
                ('slug', models.SlugField(max_length=300, unique=True, verbose_name='Slug')),
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name='Added')),
                ('views', models.IntegerField(default=0, verbose_name='Views on Hubinter')),
                ('tags', models.ManyToManyField(related_name='youtube_videos', to='videos.Tag', verbose_name='Tags')),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='videos.theme', verbose_name='Theme')),
            ],
        ),
    ]
