# Generated by Django 3.2.2 on 2021-05-20 20:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_auto_20210520_1319'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_at'], 'verbose_name': 'Comment', 'verbose_name_plural': 'Comments'},
        ),
        migrations.AddField(
            model_name='video',
            name='tags',
            field=models.ManyToManyField(related_name='videos', to='videos.Tag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='video',
            name='theme',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='videos.theme', verbose_name='Theme'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='theme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videos.theme', verbose_name='Theme'),
        ),
        migrations.AlterField(
            model_name='video',
            name='comments_amount',
            field=models.IntegerField(default=0, verbose_name='Comments'),
        ),
        migrations.AlterField(
            model_name='video',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Published'),
        ),
        migrations.AlterField(
            model_name='video',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated'),
        ),
    ]
