# Generated by Django 3.2.2 on 2021-07-18 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0003_youtubevideo_added_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='youtubevideo',
            name='preview',
            field=models.ImageField(blank=True, default='C:\\Users\\Admin\\Desktop\\Python\\HubInter\\hubinter\\media/default_pictures/default_preview.png', upload_to='youtube_previews/%Y/%m/%d/', verbose_name='YouTube Preview'),
        ),
    ]
