# Generated by Django 3.2.2 on 2021-05-24 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0003_auto_20210520_2357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='theme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='videos.theme', verbose_name='Theme'),
        ),
        migrations.AlterField(
            model_name='video',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Title'),
        ),
    ]
