# Generated by Django 3.2.2 on 2021-07-30 20:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0004_youtubevideo_preview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='comments_amount',
            field=models.PositiveIntegerField(default=0, verbose_name='Comments'),
        ),
        migrations.AlterField(
            model_name='video',
            name='dislikes',
            field=models.PositiveIntegerField(default=0, verbose_name='Dislikes'),
        ),
        migrations.AlterField(
            model_name='video',
            name='likes',
            field=models.PositiveIntegerField(default=0, verbose_name='Likes'),
        ),
        migrations.AlterField(
            model_name='video',
            name='video',
            field=models.FileField(upload_to='videos/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'webm'])], verbose_name='Video file'),
        ),
        migrations.AlterField(
            model_name='video',
            name='views',
            field=models.PositiveIntegerField(default=0, verbose_name='Views'),
        ),
        migrations.AlterField(
            model_name='youtubevideo',
            name='views',
            field=models.PositiveIntegerField(default=0, verbose_name='Views on Hubinter'),
        ),
    ]
