# Generated by Django 3.2.2 on 2021-08-19 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0006_remove_video_is_published'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
