# Generated by Django 3.2.2 on 2021-06-03 18:42

from django.conf import settings
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0007_auto_20210527_2227'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='viewed_videos',
            field=models.ManyToManyField(related_name='viewed_by', to='videos.Video', verbose_name='Viewed videos'),
        ),
        migrations.AddField(
            model_name='video',
            name='title_words_basics',
            field=models.TextField(default='', verbose_name='Basics of words in title'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='avatars/%Y/%m', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg', 'svg', 'gmp'])], verbose_name='Avatar'),
        ),
        migrations.AlterField(
            model_name='user',
            name='notifications',
            field=models.ManyToManyField(related_name='_videos_user_notifications_+', to=settings.AUTH_USER_MODEL, verbose_name='Notifications'),
        ),
        migrations.AlterField(
            model_name='video',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='Is Published'),
        ),
        migrations.AlterField(
            model_name='video',
            name='preview',
            field=models.ImageField(blank=True, upload_to='previews/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg', 'svg', 'gmp'])], verbose_name='Preview file'),
        ),
    ]
