# Generated by Django 3.2.2 on 2021-06-08 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0008_auto_20210603_2142'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='title_words_basics',
        ),
    ]
