# Generated by Django 3.2.2 on 2021-06-19 10:24

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0009_remove_video_title_words_basics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='author',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Author'),
        ),
        migrations.AlterField(
            model_name='video',
            name='description',
            field=models.TextField(max_length=2550, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='video',
            name='preview',
            field=models.ImageField(blank=True, default='C:\\Users\\Admin\\Desktop\\Python\\HubInter\\hubinter\\media/default_pictures/default_preview.png', upload_to='previews/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg', 'svg', 'gmp'])], verbose_name='Preview file'),
        ),
        migrations.AlterField(
            model_name='video',
            name='slug',
            field=models.SlugField(max_length=300, unique=True, verbose_name='Slug'),
        ),
    ]
